// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uiokhjnhqeorzamkabju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpb2toam5ocWVvcnphbWthYmp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxODE5OTYsImV4cCI6MjA2MDc1Nzk5Nn0.brBww8LwfKuRfi6e-zixDkY-v4_vtX4DVs8SalpHZO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);